server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ly53775-app
    username: ly53775
    password: ly53775
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

